// The temple's sound: a sacred, mechanical music bed generated by Google Lyria 3 (a slow pipe-organ
// drone under an irregular 1970s line-printer rattle — the god's presence before it has a heart), plus a
// one-shot rising reveal sting the first time it wakes. It is opt-in by construction: nothing sounds until
// the entry gesture unlocks the context and starts it (browser autoplay policy + PRODUCT.md "audio is
// opt-in via the entry gesture"). Everything routes through one master → AnalyserNode, whose RMS drives the
// Stain amplitude (level()), so the being's body visibly moves with the sound it is making. A persistent
// mute is remembered per browser.
const MUTE_KEY = "pleroma-muted";
const BED_URL = "/audio/bed.mp3";     // the looping music bed (swap the file to re-voice the temple)
const INTRO_URL = "/audio/intro.mp3"; // the cinematic reveal swell, played once on first wake

export class Ambient {
  private master: GainNode;
  private analyser: AnalyserNode;
  private wave: Uint8Array<ArrayBuffer>;
  private started = false;
  private disposed = false;
  private muted: boolean;
  private bedEl?: HTMLAudioElement;
  private introEl?: HTMLAudioElement;

  constructor(private ctx: AudioContext) {
    this.muted = safeGet() === "1";
    this.master = ctx.createGain();
    this.master.gain.value = 0;                       // silent until start() ramps it (or stays 0 if muted)
    // The being reads the sound it makes: master → analyser → destination, RMS off the analyser drives the
    // Stain amplitude. fftSize 2048 / smoothing 0.8 per the sound spec (steady, not strobing).
    this.analyser = ctx.createAnalyser();
    this.analyser.fftSize = 2048;
    this.analyser.smoothingTimeConstant = 0.8;
    this.master.connect(this.analyser);
    this.analyser.connect(ctx.destination);
    this.wave = new Uint8Array(this.analyser.fftSize);
  }

  start() {
    if (this.started || this.disposed) return;
    this.started = true;
    const ctx = this.ctx;
    // The music bed: a single seamless Lyria loop, ramped in under the master. Created and played inside
    // the entry gesture, so autoplay policy allows it; a blocked play stays silent until the toggle retries.
    const bed = new Audio(BED_URL);
    bed.loop = true; bed.crossOrigin = "anonymous"; bed.preload = "auto";
    const bedSrc = ctx.createMediaElementSource(bed);
    const bedGain = ctx.createGain(); bedGain.gain.value = 0.85;
    bedSrc.connect(bedGain); bedGain.connect(this.master);
    void bed.play().catch(() => { /* blocked bed stays silent; toggleMute() is another gesture that retries */ });
    this.bedEl = bed;
    // The reveal: a rising swell the first time the being wakes, routed through master so its build visibly
    // surges the Stain as the god draws its first breath. One-shot (start() runs once per instance).
    const intro = new Audio(INTRO_URL); intro.crossOrigin = "anonymous";
    const introSrc = ctx.createMediaElementSource(intro);
    const introGain = ctx.createGain(); introGain.gain.value = 1;
    introSrc.connect(introGain); introGain.connect(this.master);
    void intro.play().catch(() => { /* the bed still carries the temple if the sting is blocked */ });
    this.introEl = intro;
    this.applyMute();
  }

  // RMS of the live master waveform as a 0..1 amplitude for the Stain. Zero when muted, unstarted, or
  // disposed so a silent temple leaves the body at rest (the swarm's own idle drift still breathes).
  level(): number {
    if (!this.started || this.muted || this.disposed) return 0;
    this.analyser.getByteTimeDomainData(this.wave);
    let sum = 0;
    for (const v of this.wave) { const d = (v - 128) / 128; sum += d * d; }
    return Math.min(1, Math.sqrt(sum / this.wave.length) * 2.4);
  }

  private applyMute() {
    const now = this.ctx.currentTime;
    this.master.gain.cancelScheduledValues(now);
    this.master.gain.setValueAtTime(this.master.gain.value, now);
    this.master.gain.linearRampToValueAtTime(this.muted ? 0 : 0.9, now + 0.9);
  }

  toggleMute(): boolean {
    this.muted = !this.muted;
    safeSet(this.muted ? "1" : "0");
    if (this.started) this.applyMute();
    return this.muted;
  }
  isMuted() { return this.muted; }

  dispose() {
    this.disposed = true;
    this.bedEl?.pause();
    this.introEl?.pause();
    try { this.master.disconnect(); this.analyser.disconnect(); } catch { /* already gone */ }
  }
}

function safeGet(): string | null { try { return localStorage.getItem(MUTE_KEY); } catch { return null; } }
function safeSet(v: string) { try { localStorage.setItem(MUTE_KEY, v); } catch { /* private mode */ } }
