// The temple's sound: a sacred, mechanical music bed generated by Google Lyria 3 (a slow pipe-organ
// drone under an irregular 1970s line-printer rattle — the god's presence before it has a heart), plus a
// one-shot rising reveal sting the first time it wakes. It is opt-in by construction: nothing sounds until
// the entry gesture unlocks the context and starts it (browser autoplay policy + PRODUCT.md "audio is
// opt-in via the entry gesture"). Everything routes through one master → AnalyserNode, whose RMS drives the
// Stain amplitude (level()), so the being's body visibly moves with the sound it is making. A persistent
// mute is remembered per browser.
const MUTE_KEY = "pleroma-muted";
const BED_URL = "/audio/bed.mp3";     // the looping music bed (swap the file to re-voice the temple)
const INTRO_URL = "/audio/intro.mp3"; // the cinematic reveal swell, played once on first wake

// The Knock's own paper-fiber grain (Task 5, grown-lineage-marks §3b.6): a short synthesized
// filtered-noise burst, no new asset -- a fast-decaying noise buffer through a bandpass filter
// reads as a paper fiber's tick rather than a hiss or click. Frequency is jittered per grain so a
// fast knock's run of splits doesn't read as one sound repeating.
const GRAIN_DURATION_S = 0.045;
const GRAIN_GAIN = 0.16;
const GRAIN_FREQ_BASE = 2_600;
const GRAIN_FREQ_JITTER = 900;
const GRAIN_Q = 1.1;

// The room quiets when the god speaks: while any foreground voice plays (the sermon, an
// unmuted plate film) the bed ducks to a murmur instead of fighting the speech frequencies.
const DUCK_LEVEL = 0.1;

export class Ambient {
  private master: GainNode | null = null;
  private analyser: AnalyserNode | null = null;
  private wave: Uint8Array<ArrayBuffer> | null = null;
  private started = false;
  private disposed = false;
  private muted: boolean;
  private ducked = false;
  private bedEl?: HTMLAudioElement;
  private introEl?: HTMLAudioElement;

  constructor(private ctx: AudioContext | null) {
    this.muted = safeGet() === "1";
    if (!ctx) return;
    this.master = ctx.createGain();
    this.master.gain.value = 0;                       // silent until start() ramps it (or stays 0 if muted)
    // The being reads the sound it makes: master → analyser → destination, RMS off the analyser drives the
    // Stain amplitude. fftSize 2048 / smoothing 0.8 per the sound spec (steady, not strobing).
    this.analyser = ctx.createAnalyser();
    this.analyser.fftSize = 2048;
    this.analyser.smoothingTimeConstant = 0.8;
    this.master.connect(this.analyser);
    this.analyser.connect(ctx.destination);
    this.wave = new Uint8Array(this.analyser.fftSize);
  }

  async start(): Promise<boolean> {
    if (this.disposed) return false;
    if (!this.started) {
      this.started = true;
      const ctx = this.ctx;
      // The music bed: a single seamless Lyria loop, ramped in under the master. Created only after a
      // committed entry; subsequent explicit sound clicks reuse this element if playback was blocked.
      const bed = new Audio(BED_URL);
      bed.loop = true; bed.crossOrigin = "anonymous"; bed.preload = "auto";
      if (ctx && this.master) {
        const bedSrc = ctx.createMediaElementSource(bed);
        const bedGain = ctx.createGain(); bedGain.gain.value = 0.85;
        bedSrc.connect(bedGain); bedGain.connect(this.master);
      } else {
        bed.muted = this.muted;
      }
      this.bedEl = bed;
      this.applyMute();
    }

    const bed = this.bedEl!;
    if (bed.error) bed.load();
    const bedPlayback = bed.play();
    try {
      await bedPlayback;
      if (this.disposed || bed.paused) return false;
      let intro = this.introEl;
      if (!intro) {
        intro = new Audio(INTRO_URL); intro.crossOrigin = "anonymous";
        if (this.ctx && this.master) {
          const introSrc = this.ctx.createMediaElementSource(intro);
          const introGain = this.ctx.createGain(); introGain.gain.value = 1;
          introSrc.connect(introGain); introGain.connect(this.master);
        } else {
          intro.muted = this.muted;
        }
        this.introEl = intro;
      }
      // The reveal is one-shot when it succeeds. If its first attempt is blocked at time zero, an explicit
      // sound click may retry it alongside the bed; an ended reveal is never replayed.
      if (!intro.ended && intro.currentTime === 0) {
        if (intro.error) intro.load();
        void intro.play().catch(() => { /* the bed still carries the temple if the sting is blocked */ });
      }
      return true;
    } catch {
      return false;
    }
  }

  // True exactly when the gate the entry gesture / mute control already governs is open: the bed
  // has started, isn't muted, and this instance hasn't been disposed. Every sound this engine
  // grows beyond the bed/intro -- the grain below, and any future one -- must consult this same
  // real state rather than inventing its own activation path.
  isActive(): boolean {
    return this.started && !this.muted && !this.disposed;
  }

  // The paper-fiber grain: fired once per branch split during a live hold (ThresholdOffering's
  // 20Hz growth loop), routed through the SAME master bus as the bed/intro so the Stain's
  // amplitude reads it exactly like any other sound. A genuine no-op -- touching no audio API at
  // all -- whenever the gate above is closed; this is the one path that must never open it.
  playGrain(): void {
    if (!this.isActive() || !this.ctx || !this.master) return;
    const ctx = this.ctx;
    const frameCount = Math.max(1, Math.round(ctx.sampleRate * GRAIN_DURATION_S));
    const buffer = ctx.createBuffer(1, frameCount, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < frameCount; i += 1) {
      const decay = 1 - i / frameCount;               // fast decay -- a tick, not a tail
      data[i] = (Math.random() * 2 - 1) * decay * decay;
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    const filter = ctx.createBiquadFilter();
    filter.type = "bandpass";
    filter.frequency.value = GRAIN_FREQ_BASE + Math.random() * GRAIN_FREQ_JITTER;
    filter.Q.value = GRAIN_Q;
    const grainGain = ctx.createGain();
    grainGain.gain.value = GRAIN_GAIN;
    source.connect(filter);
    filter.connect(grainGain);
    grainGain.connect(this.master);
    source.start();
    source.stop(ctx.currentTime + GRAIN_DURATION_S);
  }

  // RMS of the live master waveform as a 0..1 amplitude for the Stain. Zero when muted, unstarted, or
  // disposed so a silent temple leaves the body at rest (the swarm's own idle drift still breathes).
  level(): number {
    if (!this.started || this.muted || this.disposed || !this.analyser || !this.wave) return 0;
    this.analyser.getByteTimeDomainData(this.wave);
    let sum = 0;
    for (const v of this.wave) { const d = (v - 128) / 128; sum += d * d; }
    return Math.min(1, Math.sqrt(sum / this.wave.length) * 2.4);
  }

  // One computed target for the master: mute always wins, then ducking, then the full bed.
  // Mute keeps its slow ceremonial ramp; ducking moves faster so the voice is clear from its
  // first word and the room swells back once it finishes.
  private applyGain(rampSeconds: number) {
    if (!this.ctx || !this.master) {
      if (this.bedEl) this.bedEl.muted = this.muted;
      if (this.introEl) this.introEl.muted = this.muted;
      return;
    }
    const now = this.ctx.currentTime;
    const target = this.muted ? 0 : this.ducked ? DUCK_LEVEL : 0.9;
    this.master.gain.cancelScheduledValues(now);
    this.master.gain.setValueAtTime(this.master.gain.value, now);
    this.master.gain.linearRampToValueAtTime(target, now + rampSeconds);
  }

  private applyMute() { this.applyGain(0.9); }

  setDucked(on: boolean): void {
    if (this.ducked === on) return;
    this.ducked = on;
    if (this.started) this.applyGain(0.45);
  }

  toggleMute(): boolean {
    this.muted = !this.muted;
    safeSet(this.muted ? "1" : "0");
    if (this.started) this.applyMute();
    return this.muted;
  }
  isMuted() { return this.muted; }

  dispose() {
    this.disposed = true;
    this.bedEl?.pause();
    this.introEl?.pause();
    try { this.master?.disconnect(); this.analyser?.disconnect(); } catch { /* already gone */ }
  }
}

function safeGet(): string | null { try { return localStorage.getItem(MUTE_KEY); } catch { return null; } }
function safeSet(v: string) { try { localStorage.setItem(MUTE_KEY, v); } catch { /* private mode */ } }

// The one Ambient instance the app has ever constructed, mirroring smoothScroll.ts's
// setActiveLenis: App.tsx's useEntryGesture owns construction/disposal (only a committed entry
// gesture or an explicit sound-control click ever calls primeAmbient), and anything downstream
// that wants to ride the SAME gated engine reaches it through here instead of prop-drilling a
// reference or -- worse -- constructing its own. Null before any entry gesture has primed audio,
// so emitGrain below is a genuine no-op until then, not a new activation path.
let activeAmbient: Ambient | null = null;
export function setActiveAmbient(ambient: Ambient | null): void {
  activeAmbient = ambient;
  ambient?.setDucked(duckHolds > 0); // a late-primed engine honors a voice already speaking
}

// Hold-counted so overlapping voices (a sermon and an unmuted plate) never fight over the bed:
// the room stays quiet until the LAST voice releases. The body attribute is the observable truth
// for tests and any future styling; it tracks the logical duck state even before audio is primed.
let duckHolds = 0;
export function duckAmbient(on: boolean): void {
  duckHolds = Math.max(0, duckHolds + (on ? 1 : -1));
  const ducked = duckHolds > 0;
  try { document.body.toggleAttribute("data-audio-ducked", ducked); } catch { /* SSR/test */ }
  activeAmbient?.setDucked(ducked);
}

// ThresholdOffering's call site for the paper-fiber grain (Task 5, grown-lineage-marks §3b.6):
// routes to the active instance's gated playGrain, or does nothing at all if no Ambient has been
// constructed yet -- exactly the same silence guarantee as the bed itself.
export function emitGrain(): void {
  activeAmbient?.playGrain();
}
