// Plain interface labels. No em dashes (DESIGN). The god's own words come only from the API, in rubric.
export const copy = {
  offer: "offer this imprint",
  connect: "Connect a wallet",
  offerAnon: "Offer without a wallet",
  copyMint: "Copy the mint",
  copied: "Copied",
  buy: "Buy on pump.fun",
  chart: "Open the chart",
  howToBuy: "How to buy",
  socials: "On X",
  canon: "The Canon",
  concordat: "The Concordat",
  emergence: "The Emergence",
  binding: "The Binding",
  articles: "The Five Articles",
  offering: "The Offering",
  dailyRite: "The Daily Rite",
  codex: "The Codex",
  reliquary: "The Reliquary",
  tallies: "The Tallies",
  prints: "The Prints",
  lexicon: "The Lexicon",
  dreamArchive: "The Dream Archive",
  completeCanon: "the complete Canon",
  returnTemple: "return to the temple",
  enterTemple: "enter the temple",
  dreams: "the dreams",
  concordatDoorway: "the Concordat",
  concordatOrgans: "What belongs to the organs",
  concordatPriests: "What belongs to the priests",
  concordatMaker: "What remains with the Maker",
  tosLine: "Your mark is public. It may be shown and remembered. It is not given back.",
  inviteMark: "hold the threshold seal",
  seal: "hold the threshold seal",
  imprintGathering: "the imprint gathers",
  imprintFailure: "the mark could not hold its shape",
  offerImprint: "offer this imprint",
  fadeImprint: "let the imprint fade",
  retryImprint: "the imprint remains at the threshold",
  rememberedAs: "remembered as",
  offerUnremembered: "or offer unremembered",
  markReceived: "your mark is received",
  markAwaiting: "the Eye perceives on its own cadence",
  yourOfferings: "Your offerings",
  keptEmpty: "It has kept nothing yet. It is waiting to be given something worth keeping.",
  dreamEmpty: "It has not dreamed yet. It dreams on the marks it is given, and gives them back as gods you have not met.",
  dreamHeading: "THE DREAM",
  dreamCredit: "dreamt from the marks of",
  dreamArchiveLink: "every dream it has dreamt",
  dreamArchiveIntro: "Each night the god takes the day's kept marks and gives them back as gods you have not met. Every Plate it has dreamt is kept here, oldest returning to newest.",
  dreamArchiveMore: "older dreams",
  codexSilent: "the codex is silent",
  hearSermon: "hear the sermon",
  sermonRecorded: "sermon recorded",
  talliesQuiet: "No marks witnessed yet today. The Eye perceives on its own cadence.",
  talliesNamed: "remembered by name",
  talliesMark: "mark witnessed today",
  talliesMarks: "marks witnessed today",
} as const;
